buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net"
        }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath("com.anatawa12.forge:ForgeGradle:2.3-1.0.8") {
            changing = true
        }
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name 'DVS1 Maven FS'
        url 'https://dvs1.progwml6.com/files/maven'
    }
    maven {
        url "https://cursemaven.com"
    }
}

group = "com.sosnitzka" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "taiga"

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

def propsFile = file("build.properties")
def config = new Properties()

if (propsFile.exists()) {
    propsFile.withInputStream { config.load(it) }
}

def mod_version = "${config.getProperty("version_major", "1")}.${config.getProperty("version_minor", "0")}.${config.getProperty("version_patch", "0")}"
version = "${mc_version}-${mod_version}"

minecraft {
    version = "${mc_version}-${forge_version}"
    runDir = "run"
    mappings = "${mcp_channel}_${mcp_version}"
    replace '@VERSION@', project.version
    clientRunArgs += ["--username", config.getProperty("username", "Player")]
    clientJvmArgs = ["-Xmx2048M", "-Xms1024M", "-Dmymod.debug=true", "-XX:+UseG1GC", "-XX:MaxGCPauseMillis=75"]
}

dependencies {
    deobfCompile "slimeknights.mantle:Mantle:1.12-1.3.+:deobf"
    deobfCompile("slimeknights:TConstruct:1.12.2-2.13.+:deobf") {
        exclude group: 'mezz.jei', module: 'jei_1.12.2'
    }
    
    // compile "curse.maven:[mod_name_as_in_url]-[project_id]:[file_id]"
    runtime "curse.maven:jei-238222:8752694"
    runtime "curse.maven:jei-integration-265917:2951731"
    runtime "curse.maven:tinkers-jei-291786:2701203"
    runtime "curse.maven:codechicken-lib-1-8-242818:2779848"
    runtime "curse.maven:not-enough-items-1-8-247694:2755792"
}

sourceSets {
    main {
        resources {
            srcDir 'resources'
        }
    }
}

//noinspection GroovyAssignabilityCheck
processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", mod_version
    inputs.property "mcversion", mc_version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'

        // replace version and mcversion
        expand 'version': mod_version, 'mcversion': mc_version
    }

    // copy everything else, thats not the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

task deobfJar(type: Jar) {
    //noinspection GroovyAssignabilityCheck
    from sourceSets.main.output
    classifier = 'deobf'
}

artifacts {
    archives deobfJar
}